### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by haplo31** [gatling/gatling-highcharts#38]
Hi,
I try to build gatling-highcharts but I have unresolved dependency messages : 
[error] (gatling-charts-highcharts/*:update) sbt.ResolveException: unresolved dependency: io.gatling#gatling-charts;2.2.0-SNAPSHOT: not found
[error] unresolved dependency: io.gatling#gatling-app;2.2.0-SNAPSHOT: not found
[error] unresolved dependency: io.gatling#gatling-recorder;2.2.0-SNAPSHOT: not found

Do you know how I can correct that ?

Thanks for your time

**Comment by slandelle** [comment]
Snapshot deployment on Sonatype is foobar. We're currently investigating.

**Comment by pdalpra** [comment]
As a workaround, you unfortunately need to clone and build locally both gatling and gatling-highcharts.

**Comment by slandelle** [comment]
We're progressively re-deploying everything.

The issue was with Travis' new docker based infrastructure.
We're reverting to the old one for now. :(

**Comment by haplo31** [comment]
Ok,
Thanks for your help and reactivity !

**Comment by pdalpra** [comment]
You're welcome :)
